### ISSUE TITLE
Update to latest version or switch to LTS?

### ISSUE THREAD

**Issue by mgcrea** [dockerfile/ubuntu#1]
Is this the new official `ubuntu` repository? How does it compare to https://index.docker.io/u/stackbrew/ubuntu/?

Anyway, this repository seems stuck on a 12.10 release. I think it should default to an upgraded 12.04 LTS (12.04.4) with an up-to-date kernel (`apt-get install linux-image-generic-lts-saucy`).

What do you think? Do you accept pull requests?

**Comment by vincentheet** [comment]
I agree with @mgcrea this Ubuntu image is nice but it should  be an LTS version (with updates). So it is better supported by the Ubuntu community. The current version (12.10) will go out of support mid-year 2014 see: https://wiki.ubuntu.com/LTS

**Comment by pilwon** [comment]
@mgcrea `Dockerfile Project` has no relation with the official Docker-supported repositories. However we do welcome PRs.

@vincentheet Staying with LTS does seem like the best way to go. One concern is, [other projects of the Dockerfile Project](http://dockerfile.github.io/) could get broken by the downgrade of this base image. We'll need to test every project after base image change and it will take some time. Do you think it's okay if we wait until the next 14.04 LTS is released next month, to avoid the duplicate work?

**Comment by vincentheet** [comment]
@pilwon I don't have issues with that but maybe it is better to think about how people will use this repo and what your intention is with it. Do you just want to use it for all the other dockerfile projects/images or do you want people to build their own stuff on top of dockerfile/ubuntu? If you want the last option it currently is not the image for them since it's not supported long enough in my opinion. If you just want to use it as a base image for the other dockerfile images then it may be fine since they don't care what the base image is as long as dockerfile/nginx just works. Although if they build up on dockerfile/nginx they also need confidence in the base image? Or you could argue that they need the newest (13.10) stuff in there...

**Comment by pilwon** [comment]
@vincentheet That's a great point. The original purpose of this base image was to provide a consistent base image for all the other Dockerfile Project images. Nevertheless, I think LTS would still be a better choice as it provides confidence in the base image for both cases. We'll remember to update this once 14.04 LTS next month, then freeze it until the subsequent LTS release.
